use_frameworks!
    
    platform :ios, '9.0'
    source 'https://github.com/CocoaPods/Specs.git'
    source 'https://github.com/XMiHu/Specs'

target 'Categories_Example' do
  pod 'Categories', :path => '../'

  target 'Categories_Tests' do
    inherit! :search_paths

    
  end
end
